DEFAULT_CONFIG = {
    "1": "hawks",
    "a": "bobcats",
    "b": "birds",
    "c": "coyote",
    "d": "deer",
    # "e": "empty",
    "f": "foxes",
    "g": "eagles",
    "h": "humans",
    "k": "skunks",
    "m": "mountain_lions",
    "o": "dogs",
    "r": "raccoons",
    "s": "squirrels",
    "u": "unknown",
    "w": "owls",
}
